Added sonar github plugin

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -13,6 +13,7 @@ BP_DIR=`cd $(dirname $0); cd ..; pwd`
 SONAR_VERSION="6.3.1"
 CODESCAN_VERSION="4.0.5"
 ANT_VERSION="1.9.9"
+GIT_PLUGIN_VERSION="1.3"
 SONAR_HOME=${BUILD_DIR}/sonarqube
 
 install_jdk() {
@@ -153,9 +154,51 @@ install_ant() {
   echo " done"
 }
 
+install_sonarqube_git() {
+  local BUILD_DIR=${1}
+  local CACHE_DIR=${2}
+
+  GITPLUGIN_DIST="sonar-scm-git-plugin-${GIT_PLUGIN_VERSION}"
+  GITPLUGIN_DIST_ZIP="${GITPLUGIN_DIST}.zip"
+  GITPLUGIN_HOME=${BUILD_DIR}/codescan
+
+  if [ ! -d ${CACHE_DIR} ]; then
+    mkdir -p ${CACHE_DIR}
+  fi
+
+  # Download CodeScan if not in cache
+  if [ ! -f ${CACHE_DIR}/${GITPLUGIN_DIST_ZIP} ]; then
+    GITPLUGIN_URL="https://sonarsource.bintray.com/Distribution/sonar-github-plugin/${GITPLUGIN_DIST_ZIP}"
+    echo -n "-----> Downloading ${GITPLUGIN_DIST}....."
+    curl --silent --location ${GITPLUGIN_URL} > ${CACHE_DIR}/${GITPLUGIN_DIST_ZIP}
+    echo " done"
+  fi
+
+  echo -n "-----> Installing ${GITPLUGIN_DIST}...."
+
+  # Unzip Codescan
+  # `unzip` command is not available.
+  cd ${BUILD_DIR}
+
+  jar xvf ${CACHE_DIR}/${GITPLUGIN_DIST_ZIP} >/dev/null
+  mv sonar-github-plugin ${CODESCAN_HOME}
+
+  cp $CODESCAN_HOME/sonar-github-plugin-$GIT_PLUGIN_VERSION.jar $SONAR_HOME/extensions/plugins
+
+  # Copy vendored antbuild.xml
+  if [ ! -f ${BUILD_DIR}/build.xml ]; then
+    cp ${BP_DIR}/etc/antbuild.xml ${BUILD_DIR}/build.xml
+  fi
+
+  if [ "${PIPESTATUS[*]}" != "0" ]; then
+    echo " !     Failed to install Sonar"
+    exit 1
+  fi
+  echo " done"
+}
+
 install_jdk ${BUILD_DIR}
 install_sonarqube ${BUILD_DIR} ${CACHE_DIR}
 install_codescan ${BUILD_DIR} ${CACHE_DIR}
 install_ant ${BUILD_DIR} ${CACHE_DIR}
-
-
+install_sonarqube_git ${BUILD_DIR} ${CACHE_DIR}
